t = "GCAGTAAGGTACTTTAGTCTGGGTGTCGCCATTGGTAGGCCATCCACAGCGAGTCCGTGATCCGACTAACATCGGGTGCGTGACTCCGCCCACATGCCCCTGATCCTGCAACGCAAGCACGAGCCAAAAGCAAACCGGTTGCGGCTGCGGTTACCTCATCGACTCGTGGTAAGAAGCCCCTAAGCCAACGGGCCTTACGAGACGGGGGATGTAAAGCGATGTATTAAAAAGAACGCCGTCACGGGCGAACTCGACGTGGGATGTTTGAATCATCGCTCAGAACTTCCGAAGTGATAAAGCGGTATTGGCGATGTGCATCACCGTCGTTATATAGTATTAAACTTACGTTAGAAACATCATCGTGCCGTACTGTATCCAACTCTTTGAAAAGTAACTATGGCTGCTATGACGAGATACCGGAGGCGCTCCTGCAGCTAGGTTCCGGGGCGCATCTAAAGTTGACACTGCAGAGGCAATTAGTGCGGCAACCATTTACGTCCTTCTACGGTCACGTTCCTACATTTAGCAAAGACTCCCCGTACGTATGCCCCATTCCAGCTAGAAGTTCAGGCTCGTCATCACTCAAAGGTGCCAGGTCTAGTCTGTAGGCTACTACTCCATGGCGACTTAAACAACGCTTACTCGGCAGTCCTCTCCCAGGAGATCGTTTGAGAAGACGCACTTCTAAGACGATAACATCTCTTATGATGGTAGATGACGCAGCCTAATAGAGGCGATGCAGCCGGTACAGCGCATAACTGTGCATGCCAAGTAACCCACGGGATAATGGCTCCGCCCACTCACTTCACCAGTCATTCTAAGGAACGATACTGTGGCAGCGCACGATCTCATCCCGGCAGGGACAAGTTAGTTCCATGATTCACAGTGCGCCAAAAGGCGAATACTTTTAAACCAGTTCACTACACTGCATCTATATTATGGCGAACGTCTTCCATTAC"

for char in t:
    if char == "A":
        # usando el end="", consigo que las letras se impriman una tras itra y no separadamente.
        print("A", end="")
    if char == "C":
        print("C", end="")
    if char == "G":
        print("G", end="")
    if char == "T":
        print("U", end="")
