s = "TTAATATGTAGGGTGAGTGGTACCAAGGTACAGGCCGAGAGGACGATTTATTATTATCGGGGCTACTACGGACTTGGTAGGCGCAATTATCAGGGCAACGTAACCGATTTCGTGACCGATTGACCTTCTCCCCTAAATCATTTCGGGCGCTACGCATTACAACACTTCCACGTCGTCTGTGCAGCCGCATACGGCTAGTTTCCTAGGGCGCGGGGTCACCCTACGTATTGGCTAGTGGGTAACCCTGAGGAGTTAGCGTAATGACGTTAGAAATTTTCTGACAAAACTATAGAGAATAGTTCCTATAGTACGGAAGAAACAAACTGCGCGTTACGAGTTGAACTTATTTGCCAAGATGGTGCTCTTACTACTCGGAAAGGCCCAAGCACGACGGCCGGTTTGACAGCCGCTGGGCGTCCGAGGGGGCCGGGAGCTGCAGACACGCATACTGGCGCCGTCGCCCCTCATGCAGTTCCGGCTATAGTTGAAGACGGTCTGGTCCGTCGGGGAGCGTTAGACATAGCAAAGTGGTCACGCATCGCATGGTCGTCCAGTTTACGGGAATGCTGAGAGACCTCACTGAGGCGTAGCCGTAGTGCGCATGGCCTTTATCACGTATCCGTTGCAATACCCACTTACGTAAGTACGATTTAATCGATAGCAACGGGACGGAATATTCGGCGCTTAGTGGTCTTATGACTATACTGACTTCTCAATCGGGGGCTACCTGTCGCAAGCTTTTTTAATGTGTTAACCAGTGCGATGACCGGAAGAGAGCGCTGGCAGCAAGACGCATTCGCCTAAGATCAGCAGTTAAAATC"

# establecemos un diccionario que marque la complementeriedad, con el replace no funciona.
comp = {"A": "T", "T": "A", "G": "C", "C": "G"}
c = ""  # creando una cadena vacía podemos ir añadiendo valores
for char in s:
    # suma y añade a la cadena vacía c los valores establecidos en el diccionario.
    c += comp[char]
# secuencia[inicio del corte:fin del corte:paso (cuantos elementos te saltas, si es negativo va hacia atrás]
sc = c[::-1]
print(sc)
